"""Seeds the app DB with members/github_mappings/tasks matching the demo
repo generated by generate_demo_repo.py, so the dashboard has a believable
story to show right after a GitHub sync: two "falling" members with
overdue/stuck tasks, three "steady" members mostly on track.

Run after generate_demo_repo.py and after pointing the team at the demo
repo (PATCH /api/github/config), then trigger a GitHub sync.

Usage:
    python scripts/seed_demo_data.py
"""

import sys
from datetime import timedelta
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from demo_config import DEMO_MEMBERS  # noqa: E402

from backend.app.db import Base, SessionLocal, engine  # noqa: E402
from backend.app.models import (  # noqa: E402
    GithubMapping,
    Member,
    SystemRole,
    Task,
    TaskStatus,
    TaskStatusHistory,
    Team,
)
from backend.app.services.invite_codes import generate_unique_invite_code  # noqa: E402
from backend.app.utils.time import utcnow  # noqa: E402

DEMO_TEAM_NAME = "Демо-команда"


def get_or_create_team(db) -> Team:
    team = db.query(Team).filter(Team.name == DEMO_TEAM_NAME).first()
    if not team:
        team = Team(name=DEMO_TEAM_NAME, invite_code=generate_unique_invite_code(db))
        db.add(team)
        db.commit()
        db.refresh(team)
    return team


def get_or_create_teamlead(db, team: Team) -> Member:
    teamlead = (
        db.query(Member)
        .filter(Member.team_id == team.id, Member.system_role == SystemRole.teamlead)
        .first()
    )
    if not teamlead:
        teamlead = Member(team_id=team.id, display_name="Тимлид", role_in_team="teamlead", system_role=SystemRole.teamlead)
        db.add(teamlead)
        db.commit()
        db.refresh(teamlead)
    return teamlead


def seed_members(db, team: Team) -> dict[str, Member]:
    members: dict[str, Member] = {}
    for cfg in DEMO_MEMBERS:
        member = db.query(Member).filter(Member.display_name == cfg["name"]).first()
        if not member:
            member = Member(
                team_id=team.id,
                display_name=cfg["name"],
                role_in_team=cfg["role"],
                system_role=SystemRole.member,
            )
            db.add(member)
            db.flush()
        if not member.github_mapping:
            db.add(GithubMapping(member_id=member.id, git_author_email=cfg["email"], git_author_name=cfg["name"]))
        members[cfg["name"]] = member
    db.commit()
    return members


def add_task(
    db,
    team: Team,
    teamlead: Member,
    assignee: Member,
    title: str,
    status: TaskStatus,
    deadline_days_from_now: int,
    status_changed_days_ago: int,
    completed_days_ago: int | None = None,
) -> None:
    now = utcnow()
    task = Task(
        team_id=team.id,
        title=title,
        assignee_member_id=assignee.id,
        created_by_member_id=teamlead.id,
        status=status,
        deadline_at=now + timedelta(days=deadline_days_from_now),
        status_changed_at=now - timedelta(days=status_changed_days_ago),
        completed_at=(now - timedelta(days=completed_days_ago)) if completed_days_ago is not None else None,
        created_at=now - timedelta(days=max(status_changed_days_ago, 1)),
    )
    db.add(task)
    db.flush()
    db.add(TaskStatusHistory(task_id=task.id, old_status=None, new_status=status, changed_by_member_id=teamlead.id))


def seed_tasks(db, team: Team, teamlead: Member, members: dict[str, Member]) -> None:
    if db.query(Task).count() > 0:
        print("Tasks already exist, skipping task seed.")
        return

    anna, boris, vera = members["Anna Volkova"], members["Boris Titov"], members["Vera Sokolova"]
    denis, egor = members["Denis Orlov"], members["Egor Panin"]

    # Steady members: mostly done-on-time, one active task each, still moving.
    add_task(db, team, teamlead, anna, "Design auth schema", TaskStatus.done, -5, 6, completed_days_ago=6)
    add_task(db, team, teamlead, anna, "Implement /api/tasks CRUD", TaskStatus.done, -2, 3, completed_days_ago=3)
    add_task(db, team, teamlead, anna, "Add GitHub sync job", TaskStatus.in_progress, 3, 1)

    add_task(db, team, teamlead, boris, "Build dashboard skeleton", TaskStatus.done, -4, 5, completed_days_ago=5)
    add_task(db, team, teamlead, boris, "Wire up score chart", TaskStatus.done, -1, 2, completed_days_ago=2)
    add_task(db, team, teamlead, boris, "Polish member detail view", TaskStatus.in_progress, 4, 1)

    add_task(db, team, teamlead, vera, "Design member card states", TaskStatus.done, -3, 4, completed_days_ago=4)
    add_task(db, team, teamlead, vera, "Design before/after screen", TaskStatus.todo, 5, 1)

    # Falling members: overdue / stuck tasks, matching their commit drop-off.
    add_task(db, team, teamlead, denis, "Refactor scoring service", TaskStatus.in_progress, -6, 9)
    add_task(db, team, teamlead, denis, "Add rate-limit handling to GitHub client", TaskStatus.todo, -2, 10)
    add_task(db, team, teamlead, denis, "Write DB migration notes", TaskStatus.done, -12, 13, completed_days_ago=13)

    add_task(db, team, teamlead, egor, "Write E2E test plan", TaskStatus.in_progress, -4, 8)
    add_task(db, team, teamlead, egor, "Automate task status regression tests", TaskStatus.in_progress, -1, 11)
    add_task(db, team, teamlead, egor, "Set up test data fixtures", TaskStatus.done, -14, 15, completed_days_ago=15)

    db.commit()


def main() -> None:
    Base.metadata.create_all(bind=engine)
    db = SessionLocal()
    try:
        team = get_or_create_team(db)
        teamlead = get_or_create_teamlead(db, team)
        members = seed_members(db, team)
        seed_tasks(db, team, teamlead, members)
        print(f"Seeded {len(members)} members and tasks for team '{team.name}' (id={team.id}).")
        print(f"Invite code: {team.invite_code} — send /start {team.invite_code} to the bot to join as teamlead's own account,")
        print("or link a real Telegram account to the teamlead row directly for testing.")
        print("Now point the team at the demo repo and sync:")
        print('  PATCH /api/github/config {"github_owner": "...", "github_repo": "..."}')
        print("  POST /api/github/sync")
        print("  POST /api/scores/recalculate")
    finally:
        db.close()


if __name__ == "__main__":
    main()
